In [433]:
import pandas as pd

In [434]:
df = pd.read_csv('finn_raw.csv')

df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116 entries, 0 to 115
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   url             116 non-null    object
 1   address         115 non-null    object
 2   total_price     115 non-null    float64
 3   asking_price    116 non-null    int64
 4   m2              116 non-null    int64
 5   rooms           103 non-null    float64
 6   bedrooms        114 non-null    float64
 7   apartment_type  116 non-null    object
 8   TBA             109 non-null    float64
 9   BRA_i           110 non-null    float64
 10  BRA_e           103 non-null    float64
 11  byggeår         99 non-null     float64
 12  fellesgjeld     78 non-null     float64
dtypes: float64(8), int64(2), object(3)
memory usage: 11.9+ KB

In [435]:
df.isnull().sum()

url                0
address            1
total_price        1
asking_price       0
m2                 0
rooms             13
bedrooms           2
apartment_type     0
TBA                7
BRA_i              6
BRA_e             13
byggeår           17
fellesgjeld       38
dtype: int64

### Henter in null values

In [436]:
df = df.dropna(subset='address')
df['total_price'] = df['total_price'].fillna(df['asking_price'] + df['fellesgjeld'])

print(df[df['bedrooms'].isna()])
df['bedrooms'] = df['bedrooms'].fillna(0)

print(df[df['rooms'].isna()])
df['rooms'] = df['rooms'].fillna(df['bedrooms'] + 1)

df = df.drop(columns=['BRA_i'])

                                                   url  \
84   https://www.finn.no/realestate/homes/ad.html?f...
107  https://www.finn.no/realestate/homes/ad.html?f...

                     address  total_price  asking_price  m2  rooms  bedrooms  \
84      Kurlandstien 2, Oslo    2888733.0       2800000  30    1.0       NaN
107  Micheletveien 38H, Oslo    3146827.0       2890000  31    1.0       NaN

    apartment_type   TBA  BRA_i  BRA_e  byggeår  fellesgjeld
84       Leilighet  32.0   30.0    2.0   1979.0      79237.0
107      Leilighet  34.0   31.0    3.0   1974.0     238967.0
                                                  url  \
0   https://www.finn.no/realestate/homes/ad.html?f...
4   https://www.finn.no/realestate/homes/ad.html?f...
11  https://www.finn.no/realestate/homes/ad.html?f...
44  https://www.finn.no/realestate/project/ad.html...
45  https://www.finn.no/realestate/project/ad.html...
46  https://www.finn.no/realestate/project/ad.html...
47  https://www.finn.no/realestate/project/ad.html...
55  https://www.finn.no/realestate/homes/ad.html?f...
60  https://www.finn.no/realestate/homes/ad.html?f...
85  https://www.finn.no/realestate/homes/ad.html?f...
91  https://www.finn.no/realestate/project/ad.html...
92  https://www.finn.no/realestate/project/ad.html...
93  https://www.finn.no/realestate/project/ad.html...

                            address  total_price  asking_price   m2  rooms  \
0           Furuset allé 19 A, Oslo    9215840.0       8990000  166    NaN
4             Skanseveien 8 E, Oslo    9933340.0       9690000  220    NaN
11              Jerikoveien 1, Oslo    3893147.0       3490000   59    NaN
44            Jerikoveien 93A, Oslo    5543940.0       4990000  107    NaN
45            Jerikoveien 93A, Oslo    5543940.0       4990000  107    NaN
46           Risløkkfaret 9 A, Oslo   17063200.0      16900000  196    NaN
47            Jerikoveien 93A, Oslo    5543940.0       4990000  107    NaN
55            Kløfterhagen 7H, Oslo    7165840.0       6990000  160    NaN
60              Jerikoveien 1, Oslo    3616096.0       3250000   46    NaN
85                  Kleiva 7B, Oslo    8970140.0       8750000  136    NaN
91  Erling Michelsens vei 19B, Oslo    6311832.0       5590000  111    NaN
92  Erling Michelsens vei 19B, Oslo    6311832.0       5590000  111    NaN
93  Erling Michelsens vei 19B, Oslo    6311832.0       5590000  111    NaN

    bedrooms apartment_type    TBA  BRA_i  BRA_e  byggeår  fellesgjeld
0        4.0       Enebolig  166.0  166.0    NaN   2025.0          NaN
4        3.0   Tomannsbolig  250.0  220.0   30.0   2008.0          NaN
11       1.0      Leilighet   65.0   59.0    6.0   1977.0     393651.0
44       4.0      Leilighet    NaN    NaN    NaN      NaN          NaN
45       4.0      Leilighet    NaN    NaN    NaN      NaN          NaN
46       4.0       Enebolig  196.0  196.0    NaN      NaN          NaN
47       4.0      Leilighet    NaN    NaN    5.0      NaN          NaN
55       3.0       Enebolig  180.0  160.0   20.0   1980.0          NaN
60       1.0      Leilighet   51.0   46.0    5.0   1977.0     347400.0
85       3.0       Enebolig  165.0  136.0   29.0   1981.0          NaN
91       3.0       Rekkehus    NaN    NaN    NaN      NaN          NaN
92       3.0       Rekkehus    NaN    NaN    5.0      NaN          NaN
93       3.0       Rekkehus    NaN    NaN    NaN      NaN          NaN

In [437]:
print(df[df['BRA_e'].isna()])
df['BRA_e'] = df['BRA_e'].fillna(0)

df.isnull().sum()

df['TBA'] = df['TBA'].fillna(df['m2'] + df['BRA_e'])


print(df[df['byggeår'].isna()])
df['byggeår'] = df['byggeår'].fillna(2027)

df.isnull().sum()

                                                   url  \
0    https://www.finn.no/realestate/homes/ad.html?f...
44   https://www.finn.no/realestate/project/ad.html...
45   https://www.finn.no/realestate/project/ad.html...
46   https://www.finn.no/realestate/project/ad.html...
52   https://www.finn.no/realestate/homes/ad.html?f...
64   https://www.finn.no/realestate/homes/ad.html?f...
77   https://www.finn.no/realestate/homes/ad.html?f...
87   https://www.finn.no/realestate/homes/ad.html?f...
90   https://www.finn.no/realestate/homes/ad.html?f...
91   https://www.finn.no/realestate/project/ad.html...
93   https://www.finn.no/realestate/project/ad.html...
108  https://www.finn.no/realestate/homes/ad.html?f...
113  https://www.finn.no/realestate/homes/ad.html?f...

                             address  total_price  asking_price   m2  rooms  \
0            Furuset allé 19 A, Oslo    9215840.0       8990000  166    5.0
44             Jerikoveien 93A, Oslo    5543940.0       4990000  107    5.0
45             Jerikoveien 93A, Oslo    5543940.0       4990000  107    5.0
46            Risløkkfaret 9 A, Oslo   17063200.0      16900000  196    5.0
52               Bredes vei 6C, Oslo    7165840.0       6990000  127    4.0
64                Kringveien 3, Oslo    7688590.0       7500000  139    3.0
77               Pionerstien 8, Oslo    5469239.0       4900000   84    3.0
87          Ellingsrudveien 1A, Oslo    6756100.0       6590000  172    4.0
90          Vardeheimveien 24C, Oslo    5433590.0       5300000   86    4.0
91   Erling Michelsens vei 19B, Oslo    6311832.0       5590000  111    4.0
93   Erling Michelsens vei 19B, Oslo    6311832.0       5590000  111    4.0
108             Linjeveien 51C, Oslo   11943850.0      11650000  255    7.0
113             Hesjeveien 19A, Oslo    9431090.0       9200000  191    8.0

     bedrooms apartment_type    TBA  BRA_e  byggeår  fellesgjeld
0         4.0       Enebolig  166.0    NaN   2025.0          NaN
44        4.0      Leilighet    NaN    NaN      NaN          NaN
45        4.0      Leilighet    NaN    NaN      NaN          NaN
46        4.0       Enebolig  196.0    NaN      NaN          NaN
52        3.0       Enebolig  127.0    NaN   1988.0          NaN
64        2.0   Tomannsbolig  139.0    NaN   1962.0          NaN
77        2.0      Leilighet   84.0    NaN   1980.0     559743.0
87        3.0       Enebolig  172.0    NaN   1980.0          NaN
90        3.0      Leilighet   86.0    NaN   2018.0          NaN
91        3.0       Rekkehus    NaN    NaN      NaN          NaN
93        3.0       Rekkehus    NaN    NaN      NaN          NaN
108       4.0       Enebolig  255.0    NaN   1987.0          NaN
113       6.0       Enebolig  191.0    NaN   1953.0          NaN
                                                   url  \
44   https://www.finn.no/realestate/project/ad.html...
45   https://www.finn.no/realestate/project/ad.html...
46   https://www.finn.no/realestate/project/ad.html...
47   https://www.finn.no/realestate/project/ad.html...
48   https://www.finn.no/realestate/projectsingle/a...
49   https://www.finn.no/realestate/projectsingle/a...
91   https://www.finn.no/realestate/project/ad.html...
92   https://www.finn.no/realestate/project/ad.html...
93   https://www.finn.no/realestate/project/ad.html...
94   https://www.finn.no/realestate/projectsingle/a...
95   https://www.finn.no/realestate/projectsingle/a...
97   https://www.finn.no/realestate/projectsingle/a...
98   https://www.finn.no/realestate/projectsingle/a...
99   https://www.finn.no/realestate/projectsingle/a...
114  https://www.finn.no/realestate/projectsingle/a...
115  https://www.finn.no/realestate/projectsingle/a...

                                               address  total_price  \
44                               Jerikoveien 93A, Oslo    5543940.0
45                               Jerikoveien 93A, Oslo    5543940.0
46                              Risløkkfaret 9 A, Oslo   17063200.0
47                               Jerikoveien 93A, Oslo    5543940.0
48                                Granstangen 23, Oslo    5985720.0
49                                Granstangen 23, Oslo    5887900.0
91                     Erling Michelsens vei 19B, Oslo    6311832.0
92                     Erling Michelsens vei 19B, Oslo    6311832.0
93                     Erling Michelsens vei 19B, Oslo    6311832.0
94                                Granstangen 23, Oslo    5605020.0
95                                Granstangen 23, Oslo    7009420.0
97   Furuset Village - leil B2010 *mulighet for OBO...    3409445.0
98                                Granstangen 23, Oslo    6498745.0
99   Furuset Village leil 5001 *Mulighet for Deleie...    6469445.0
114  Frysjaveien 38 A - Ager borettslag - Leilighet...    9562238.0
115                               Granstangen 23, Oslo    6427900.0

     asking_price   m2  rooms  bedrooms apartment_type    TBA  BRA_e  byggeår  \
44        4990000  107    5.0       4.0      Leilighet  107.0    0.0      NaN
45        4990000  107    5.0       4.0      Leilighet  107.0    0.0      NaN
46       16900000  196    5.0       4.0       Enebolig  196.0    0.0      NaN
47        4990000  107    5.0       4.0      Leilighet  112.0    5.0      NaN
48        5950000   80    4.0       3.0      Leilighet   85.0    5.0      NaN
49        5850000   59    3.0       2.0      Leilighet   64.0    5.0      NaN
91        5590000  111    4.0       3.0       Rekkehus  111.0    0.0      NaN
92        5590000  111    4.0       3.0       Rekkehus  116.0    5.0      NaN
93        5590000  111    4.0       3.0       Rekkehus  111.0    0.0      NaN
94        5590000   50    2.0       1.0      Leilighet   62.0    5.0      NaN
95        6990000   67    3.0       2.0      Leilighet   80.0    5.0      NaN
97        1360000   33    2.0       1.0      Leilighet   33.0    2.0      NaN
98        6470000   59    3.0       2.0      Leilighet   64.0    5.0      NaN
99        2584000   74    4.0       3.0      Leilighet   74.0    5.0      NaN
114       4530000   88    3.0       2.0      Leilighet   93.0    5.0      NaN
115       6390000   59    3.0       2.0      Leilighet   64.0    5.0      NaN

     fellesgjeld
44           NaN
45           NaN
46           NaN
47           NaN
48           NaN
49           0.0
91           NaN
92           NaN
93           NaN
94           0.0
95           0.0
97     2040000.0
98           NaN
99     3876000.0
114    4970000.0
115          0.0

url                0
address            0
total_price        0
asking_price       0
m2                 0
rooms              0
bedrooms           0
apartment_type     0
TBA                0
BRA_e              0
byggeår            0
fellesgjeld       38
dtype: int64

### Removing unnecessary features

In [438]:
print(df.columns)
df = df.drop(columns=['fellesgjeld', 'asking_price', 'url'])
df.head()

Index(['url', 'address', 'total_price', 'asking_price', 'm2', 'rooms',
       'bedrooms', 'apartment_type', 'TBA', 'BRA_e', 'byggeår', 'fellesgjeld'],
      dtype='object')

,address,total_price,m2,rooms,bedrooms,apartment_type,TBA,BRA_e,byggeår
0,"Furuset allé 19 A, Oslo",9215840.0,166,5.0,4.0,Enebolig,166.0,0.0,2025.0
1,"Linjeveien 19B, Oslo",12813890.0,215,8.0,3.0,Enebolig,253.0,38.0,1977.0
2,"Henrik Sørensens vei 9, Oslo",3389645.0,45,2.0,1.0,Leilighet,47.0,2.0,1972.0
3,"Trygve Nilsens vei 30G, Oslo",6668654.0,111,4.0,3.0,Rekkehus,114.0,3.0,1981.0
4,"Skanseveien 8 E, Oslo",9933340.0,220,4.0,3.0,Tomannsbolig,250.0,30.0,2008.0

### Removing duplicates

In [439]:
print(df.shape)
print('Number of duplicate rows:', df.duplicated().sum())
df[df.duplicated(keep=False)]

(115, 9)
Number of duplicate rows: 2

,address,total_price,m2,rooms,bedrooms,apartment_type,TBA,BRA_e,byggeår
44,"Jerikoveien 93A, Oslo",5543940.0,107,5.0,4.0,Leilighet,107.0,0.0,2027.0
45,"Jerikoveien 93A, Oslo",5543940.0,107,5.0,4.0,Leilighet,107.0,0.0,2027.0
91,"Erling Michelsens vei 19B, Oslo",6311832.0,111,4.0,3.0,Rekkehus,111.0,0.0,2027.0
93,"Erling Michelsens vei 19B, Oslo",6311832.0,111,4.0,3.0,Rekkehus,111.0,0.0,2027.0

In [440]:
df = df.drop_duplicates()
df.shape

(113, 9)

#### Changing  name on columns and cells

In [441]:
df["total_price"] = df["total_price"].astype(int)
df["rooms"] = df["rooms"].astype(int)
df["bedrooms"] = df["bedrooms"].astype(int)
df["TBA"] = df["TBA"].astype(int)
df["BRA_e"] = df["BRA_e"].astype(int)
df["byggeår"] = df["byggeår"].astype(int)

df.head()

,address,total_price,m2,rooms,bedrooms,apartment_type,TBA,BRA_e,byggeår
0,"Furuset allé 19 A, Oslo",9215840,166,5,4,Enebolig,166,0,2025
1,"Linjeveien 19B, Oslo",12813890,215,8,3,Enebolig,253,38,1977
2,"Henrik Sørensens vei 9, Oslo",3389645,45,2,1,Leilighet,47,2,1972
3,"Trygve Nilsens vei 30G, Oslo",6668654,111,4,3,Rekkehus,114,3,1981
4,"Skanseveien 8 E, Oslo",9933340,220,4,3,Tomannsbolig,250,30,2008

In [442]:
df["address"] = (
    df["address"]
    .str.split(r"[,\-\d]", n=1, regex=True)
    .str[0]
    .str.strip()
)
df

,address,total_price,m2,rooms,bedrooms,apartment_type,TBA,BRA_e,byggeår
0,Furuset allé,9215840,166,5,4,Enebolig,166,0,2025
1,Linjeveien,12813890,215,8,3,Enebolig,253,38,1977
2,Henrik Sørensens vei,3389645,45,2,1,Leilighet,47,2,1972
3,Trygve Nilsens vei,6668654,111,4,3,Rekkehus,114,3,1981
4,Skanseveien,9933340,220,4,3,Tomannsbolig,250,30,2008
...,...,...,...,...,...,...,...,...,...
111,Ole Reistads vei,5423696,96,4,3,Leilighet,99,3,1978
112,Erling Michelsens vei,5888696,111,4,3,Leilighet,115,4,1981
113,Hesjeveien,9431090,191,8,6,Enebolig,191,0,1953
114,Frysjaveien,9562238,88,3,2,Leilighet,93,5,2027
115,Granstangen,6427900,59,3,2,Leilighet,64,5,2027

In [443]:
df = df.rename(columns={
    "address": "gatenavn",
    "m2": "internt_bruksareal",
    "TBA": "bruksareal",
    "BRA_e": "terrasseareal",
    "apartment_type": "leilighetstype",
    "total_price": "totalpris",
    "rooms": "rom",
    "bedrooms": "soverom",
    "byggeår": "byggeår"
})

df

,gatenavn,totalpris,internt_bruksareal,rom,soverom,leilighetstype,bruksareal,terrasseareal,byggeår
0,Furuset allé,9215840,166,5,4,Enebolig,166,0,2025
1,Linjeveien,12813890,215,8,3,Enebolig,253,38,1977
2,Henrik Sørensens vei,3389645,45,2,1,Leilighet,47,2,1972
3,Trygve Nilsens vei,6668654,111,4,3,Rekkehus,114,3,1981
4,Skanseveien,9933340,220,4,3,Tomannsbolig,250,30,2008
...,...,...,...,...,...,...,...,...,...
111,Ole Reistads vei,5423696,96,4,3,Leilighet,99,3,1978
112,Erling Michelsens vei,5888696,111,4,3,Leilighet,115,4,1981
113,Hesjeveien,9431090,191,8,6,Enebolig,191,0,1953
114,Frysjaveien,9562238,88,3,2,Leilighet,93,5,2027
115,Granstangen,6427900,59,3,2,Leilighet,64,5,2027

In [444]:
df = df[['totalpris','internt_bruksareal', 'terrasseareal', 'rom','byggeår', 'gatenavn']]
df.to_csv("finn_data_cleaned.csv", index=False)